services:
  portfolio:
    image: ghcr.io/mvoemel/portfolio:latest
    container_name: portfolio
    pull_policy: always # ensures updates check every time 'up' is run
    restart: unless-stopped
    ports:
      - '3000:80'

  watchtower:
    image: nickfedor/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    command: portfolio
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=300 # sec
      - WATCHTOWER_CLEANUP=true
      - TZ=UTC
